### ISSUE TITLE
Do I need to add PostCSS to cookiecutter.json?

### ISSUE THREAD

**Issue by vladimirmyshkovski** [vchaptsev/cookiecutter-django-vue#11]
I believe that the front-end configuration requires PostCSS.

Do you think this is necessary, or let the user himself choose whether he needs it?

**Comment by vchaptsev** [comment]
Hey, @narnikgamarnikus 
As far as I know, vue-loader is using PostCSS by default

More info: [vue-loader docs](https://vue-loader.vuejs.org/en/features/postcss.html)
