### ISSUE TITLE
py.test fails

### ISSUE THREAD

**Issue by mtmvu** [vchaptsev/cookiecutter-django-vue#12]
It's more related to the original django cookiecutter but i post it here though:

Running the command:
`docker-compose run django py.test`
returns several errors all related to 
```
       django.db.utils.OperationalError: could not connect to server: No such file or directory
       	Is the server running locally and accepting
       	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
```
From the following line:
https://github.com/vchaptsev/cookiecutter-django-vue/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/config/settings/base.py#L104

it seems that `env.db('DATABASE_URL')` is not set and the default url is not correct.
I had to change to: 
```python
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': '{{cookiecutter.project_slug}}',
        'USER': '{{cookiecutter.project_slug}}',
        'HOST': 'postgres',
        'PORT': 5432
    }
}
```

to make it works. Did i make something wrong during the build process? (No other part of the code has been modified)

I'm on MacOS High Sierra running lastest version of docker

**Comment by vchaptsev** [comment]
Hey, @mtmvu 
Thank you for the report! 😄 

Just tried to reproduce the error, everything seems to work fine (same environment)

___
Can you please try to repeat these steps?

1. **Create a project** (actual version)
`cookiecutter gh:/vchaptsev/cookiecutter-django-vue`

2. **Build the project:**
`docker-compose build`

3. **Start the project** (database creation):
`docker-compose up -d`

4. **Run the tests:**
`docker-compose run django py.test`


___


The causes of the bug that I can imagine:
+ Bug in an earlier version
+ Really strange project_slug
+ Tests were run before the database was created

**Comment by mtmvu** [comment]
Thank you for your answer 👍 

Running exactly your commands work.

This sequence will fail on tests, i don't know why:
```
cookiecutter gh:/vchaptsev/cookiecutter-django-vue
docker-compose build
docker-compose up # no detached mode
docker-compose exec django py.test
```

But if i run in another console:
`docker-compose run django py.test`
This will work.

After that, the first console where the docker is still running would infinitely log (even if i restart the container) :
```
postgres_1      | ERROR:  database "test_myproject" already exists
postgres_1      | STATEMENT:  CREATE DATABASE "test_myproject"
```
(I need non detached mode for debugging.)

edit: the infinite logs disappear when killing all containers then running `docker-compose up`. So i guess everything is fine for now. I just need to make sure to stop the containers before running `docker-compose run django py.test`.  Thank you
