### ISSUE TITLE
Why are you ignored by Celery and Opbeat?

### ISSUE THREAD

**Issue by vladimirmyshkovski** [vchaptsev/cookiecutter-django-vue#2]
Hello.
I really like what you are doing and I have a few questions:

1) Why did you abandon Celery?
I use it in almost every project, and, it seems to me, this is an extremely necessary element of the cookiecutter

2) Why did you abandon Opbeat?
I often use opbeat and sentry together, and do not see a problem asking the user if he wants to have it or not.

3) Why not use Whitenoise?
I had problems with AWS and I had to give out my meda with whitenoise. Yes, there are not enough statics in SPA, but there is still a lot of media, and to give the opportunity to use whitenoise, in my opinion - not a bad idea.

4) I really like mdbootstrap, but it does not yet support Vue, but right now we could provide vue-bootstrap as a possible choice. Why not ?

I think giving as many opportunities as possible is a good idea.

How do you think ?

**Comment by vchaptsev** [comment]
Hey, @narnikgamarnikus 
Thanks for your feedback!

> I think giving as many opportunities as possible is a good idea.

Yeah, totally agree. I have many plans, next ones:

- Whitenoise
- Opbeat
- Google Analytics (as analog of Yandex Metrika)
- Webpack config refactor


> I had to give out my meda with whitenoise

Hm, I dont think you can really use whitenoise to [serve media files](https://github.com/evansd/whitenoise/issues/32)


> Why did you abandon Celery?

I have nothing against Celery, may be at one day (or you can contribute 😄  )


> I really like mdbootstrap, but it does not yet support Vue

You can use [vuematerial.io](http://vuematerial.io/)!
