### ISSUE TITLE
Automated postgres backups

### ISSUE THREAD

**Issue by vchaptsev** [vchaptsev/cookiecutter-django-vue#23]

**Comment by sobolevn** [comment]
Hi! I am using pretty similar setup with https://github.com/wemake-services/wemake-django-template/blob/master/%7B%7Bcookiecutter.project_name%7D%7D/docker-compose.yml
And I am looking for some best practices.

How do you handle backups for your projects? Do you use any automated tools or external services?
Thanks!

**Comment by vchaptsev** [comment]
Hey, @sobolevn 
Usually I use simple solutions like [this](https://github.com/schickling/dockerfiles/tree/master/postgres-backup-s3) or [this](https://github.com/prodrigestivill/docker-postgres-backup-local)

P.S. Your report about python dependencies was cool :)
P.P.S. I really like your approach in wemake-services
