### ISSUE TITLE
Frontend is not working

### ISSUE THREAD

**Issue by robert197** [vchaptsev/cookiecutter-django-vue#24]
After the installation and starting docker-compose i cannot open the app.
When i go to localhost:3000 my browser says. "cannot open / GET" 
when i go to localhost:8000 i get folowing error message inside browser console.

``Failed to load resource: the server responded with a status of 404 (Not Found)
localhost/:1 Refused to execute script from 'http://localhost:3000/static/dist/bundle.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.``

**Comment by vchaptsev** [comment]
Whooops
Thanks, @robert197 
Fixed in 3903c20
