### ISSUE TITLE
How to run python manage.py createsuperuser?

### ISSUE THREAD

**Issue by robbiibadi** [vchaptsev/cookiecutter-django-vue#25]
please help me, i wan to create superuser, how to create it ? thank you

**Comment by vchaptsev** [comment]
Hey, @robbiibadi 
Try something like this:
```bash
docker-compose run django python manage.py createsuperuser
```
This code runs 'python manage.py createsuperuser' in `django` container

**Comment by robbiibadi** [comment]
its work thank you @vchaptsev

**Comment by ghost** [comment]
Hi @vchaptsev 

Me again, I tried running that command and I get this error:

No such service: django

Any suggestions?

**Comment by vchaptsev** [comment]
Hey!

Now it is `backend`

```python
docker-compose run backend python manage.py createsuperuser
```

**Comment by ghost** [comment]
Hi @vchaptsev 

Successfully created a user - one more question. How do I access the vue-cli from docker?

Kind Regards 

Werner

**Comment by vchaptsev** [comment]
Something like this:

```bash
docker-compose run frontend <your command>

# for example:
docker-compose run frontend npm run lint
```

**Comment by ghost** [comment]
Okay awesome! It worked - thank you so much for helping me out.

**Comment by nregard** [comment]
docker-compose run backend python manage.py createsuperuser

gives me ERROR: No such service: backend

both commands don't work for me. Any other ideas?

**Comment by nregard** [comment]
Nevermind I found a solution

First ran this migrate command  - this is the only one that worked for in a docker container:
`sudo docker-compose run web python manage.py migrate`

Then ran this command:
`docker exec -it <dockercontainerid> python manage.py createsuperuser`

**Comment by ITKenya** [comment]
Hi,
What do I type in the prompt after I run the docker-compose run backend python manage.py createsuperuser command?

**Comment by tpchris1** [comment]
Although this issue is closed long time ago
But as for me using latest docker(unsure which version)
I simply run a create_admin.py using
`CMD [ "python", "create_admin.py"]`
in that create_admin.py
```py
from django.contrib.auth import get_user_model

User = get_user_model()
User.objects.create_superuser('admin', 'admin@gmail.com', 'admin')
```

Just for some reference and some random comment.
Hope this helps.

**Comment by sklearn21** [comment]
this worked for me....i m using docker and was unable to create superuser with 
===> docker-compose run app sh -c "python manage.py createsuperuser"
![Screenshot (220)](https://user-images.githubusercontent.com/58293384/70506083-866edc00-1b4f-11ea-9e3c-9818081d1970.png)

**Comment by canberkeh** [comment]
> Nevermind I found a solution
> 
> First ran this migrate command - this is the only one that worked for in a docker container:
> `sudo docker-compose run web python manage.py migrate`
> 
> Then ran this command:
> `docker exec -it <dockercontainerid> python manage.py createsuperuser`


it helped me alot ! tyvm !
