### ISSUE TITLE
Running Locally

### ISSUE THREAD

**Issue by ghost** [vchaptsev/cookiecutter-django-vue#26]
Hi There

First of all **thank you** for keeping this repo up to date. I have 2 questions:
(Sorry if these questions come across as stupid, I've never used docker before)

1) Do I have to use docker to develop locally/deploy? If not, what steps to I need do take to make sure all my dependencies are installed?

2) If I use docker locally can I deploy on pythonanywhere, so basically deploy without docker?

I have a pythonanywhere account and would like to utilize it if possible.

**Comment by vchaptsev** [comment]
Hey, @wernerkotze !
You are welcome 😄 

In short:
--------
1. Yes, using of docker is implied
2. I am not sure, but I don't think it is possible 😞 

Life without Docker
-------------------
But if you really want to use it without docker, you have to do some changes:
1. Modify settings
You can hardcode, but if you want to keep them `environment`-based you can use [django-environ](https://github.com/joke2k/django-environ/) package (it is in requirements already)
```python
env.read_envfile()
```

2. Install & start all required services (postgres, nginx, etc)
3. Configure nginx (services domains & ports)

Further steps
--------------
If you will have some questions\problems, do not hesitate to ask them 😄
If you manage to go through this difficult path – it would be cool to document this

P.S. docker is great, I'd highly recommend you to give it a try

**Comment by wernerkotze** [comment]
Hi There @vchaptsev 

Thank you for replying! In the mean time I decided to try out Docker - it looks really cool :1st_place_medal: 

But I cannot seem to get past this error (I don't think my ports are being set):

topnot_nginx_1 exited with code 1
frontend_1  | npm WARN babel-loader@8.0.2 requires a peer of @babel/core@^7.0.0 but none is installed. You must install peer dependencies yourself.
frontend_1  | npm WARN eslint-config-standard@12.0.0 requires a peer of eslint@>=5.0.0 but none is installed. You must install peer dependencies yourself.
frontend_1  | npm WARN eslint-config-standard@12.0.0 requires a peer of eslint-plugin-node@>=7.0.0 but none is installed. You must install peer dependencies yourself.
frontend_1  | npm WARN eslint-config-standard@12.0.0 requires a peer of eslint-plugin-promise@>=4.0.0 but none is installed. You must install peer dependencies yourself.
frontend_1  | npm WARN eslint-config-standard@12.0.0 requires a peer of eslint-plugin-standard@>=4.0.0 but none is installed. You must install peer dependencies yourself.
frontend_1  | npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
frontend_1  | npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
frontend_1  | 
frontend_1  | audited 33357 packages in 10.785s
frontend_1  | found 0 vulnerabilities
frontend_1  | 
frontend_1  |  INFO  Starting development server...
frontend_1  |  10% building modules 0/1 modules 1 active ...ck/hot/only-dev-ser 10% building modules 1/2 modules 1 active ...ndex.js?http://0.0.0.0:8000/sockj 10% building modules 1/3 modules 2 active .......................MORE OF THIS..........................................modules 129/140 modules 11 active /app/node_modules/is-buffer/ind 25% building modules 130/140 modules 10 active /app/node_modules/is-buffer/ind 25% building modules 131/140 modules 9 active /app/node_modules/is-buffer/inde 25% building modules 132/140 modules 8 active /app/node_modules/is-buffer/inde 25% building modules 133/140 modules 7 active /app/node_modules/is-buffer/inde 26% building modules 134/140 modules 6 active /app/node_modules/is-buffer/inde 26% building modules 135/140 modules 5 active /app/node_modules/is-buffer/inde 26% building modules 136/140 modules 4 active /app/node_modules/is-buffer/inde 26% building modules 137/140 modules 3 active /app/node_modules/is-buffer/inde 26% building modules 138/140 modules 2 active /app/node_modules/is-buffer/inde 26% building modules 138/141 modules 3 active ...p/node_modules/path-browserif 26% building modules 139/141 modules 2 active ...p/node_modules/path-browserif 26% building modules 140/141 modules 1 active ...p/node_modules/path-browserif 26% building modules 140/142 modules 2 active ...ore-js/modules/_object-keys-i 26% building modules 140/143 modules 3 active ..._modules/axios/lib/core/enhan 26% building modules 141/143 modules 2 active ..._modules/axios/lib/core/enhan 27% building modules 142/143 modules 1 active ...ore-js/modules/_object-keys-i 27% building modules 143/144 modules 1 active ...node_modules/css-loader/lib/c 27% building modules 143/145 modules 2 active ...ules/core-js/modules/_array-i 27% building modules 144/145 modules 1 active ...ules/core-js/modules/_array-i 27% building modules 145/146 modules 1 active ...s/core-js/modules/_to-absolut 98% after emitting CopyPlugin DONE  Compiled successfully in 1689ms7:05:17 PM
frontend_1  | 
              
frontend_1  |   App running at:
frontend_1  |   - Local:   http://localhost:8080/ 
frontend_1  | 
frontend_1  |   It seems you are running Vue CLI inside a container.
frontend_1  |   Access the dev server via http://localhost:<your container's external mapped port>/
frontend_1  | 
frontend_1  |   Note that the development build is not optimized.
frontend_1  |   To create a production build, run npm run build.
frontend_1  |

**Comment by vchaptsev** [comment]
Hey!

Let's try to debug it :)
First of all, change this in `docker-compose.yml`:
```python
 nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    depends_on:
      - backend
    volumes:
      - ./backend/media/:/media/
      - ./backend/staticfiles/:/staticfiles/
      - ./nginx/dev.conf:/etc/nginx/nginx.conf:ro
    logging:
      driver: none
```

to this:
```python
 nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    depends_on:
      - backend
    volumes:
      - ./backend/media/:/media/
      - ./backend/staticfiles/:/staticfiles/
      - ./nginx/dev.conf:/etc/nginx/nginx.conf:ro
```

And send me new logs

**Comment by ghost** [comment]
Hi There

So I removed:

 logging:
      driver: none

and still received the same error logs. Is it worth mentioning that I'm running on Ubuntu 18.04?

**Comment by vchaptsev** [comment]
Oh, well.
Can you provide me a sample repo?

P.S. double check ports 😄

**Comment by ghost** [comment]
@vchaptsev 

Thank you for all your help - will double check the ports and do some more debugging to see if I can find anything. Going to try and create a basic django project with docker to see if the problem is with my machine.

Kind Regards

**Comment by Mike97M** [comment]
I had the same problem, it's because there is syntax error made in dev.conf on line 44: 
`location ~ ^/(admin|{% if cookiecutter.api == "REST" %}api{% elif cookiecutter.api == "GraphQL" %}graphql{% endif %}) {) {`

The problem is `{)` after I've removed that everything worked fine.

Edit: I've submitted a pull request: #27

**Comment by vchaptsev** [comment]
Thanks you, @Mike97M 
Bug is fixed now 🎈

**Comment by ghost** [comment]
@vchaptsev @Mike97M 

Got everything working on my side! Thanks for the input my dudes.
