### ISSUE TITLE
Subdomain support

### ISSUE THREAD

**Issue by briancaffey** [vchaptsev/cookiecutter-django-vue#28]
Hi, cool project. Do you have plans to support subdomains? I'm working on a similar project and I am working on how to set up subdomain support. From what I have seen, I think it can be done with a middleware class on the Django side, some processing of the URL in Vue's router and editing nginx to catch the subdomains.

**Comment by vchaptsev** [comment]
Hey, thank you :)

Subdomains
------------
Yeah, your approach seems good for me.
You may also use [Django Sites Framework](https://docs.djangoproject.com/en/2.1/ref/contrib/sites/).

Support
--------
I don't know.
Subdomains support is not _very basic_ functionality, so I'm not sure if it is should be in cookiecutter.
But if you want to contribute – it would be great 😄

**Comment by vchaptsev** [comment]
Let's say it's out of scope
