### ISSUE TITLE
Vuex Login 

### ISSUE THREAD

**Issue by ghost** [vchaptsev/cookiecutter-django-vue#29]
Hey @vchaptsev 

This is honestly not your problem at all so I'm trying my luck a bit here. I can't seem to call an action using vuex via a template. Do you maybe have an example of how you do the postLogin action on a component?

If you want to see how I setup my code for the login it's here:

https://stackoverflow.com/questions/52709493/vue-js-vuex-login-vuex-unknown-action-type-postlogin

Thanks Again

**Comment by vchaptsev** [comment]
Hey! 
Feel free to ask any question 😄 
Can you share your repo? It would be a lot easier to debug.

I will try to figure it out in the evening!

**Comment by ghost** [comment]
Hi @vchaptsev 

Thank you so much my dude, I really appreciate it!

It's currently on bitbucket. I will make a clone of it and put it on github this evening. Will let you know once it's up :)

Kind Regards

Werner

**Comment by wernerkotze** [comment]
Hey @vchaptsev 

I uploaded my repo to github:

https://github.com/wernerkotze/djangovue

**Comment by ghost** [comment]
@vchaptsev 

Can I rather invite you to the bitbucket repo?

**Comment by vchaptsev** [comment]
Yeah, of course :)
If you need my email: victor@chaptsev.ru

**Comment by ghost** [comment]
Okay cool, I sent an invite to your email. Let me know when you get it :) The login component is on branch TN-01. @vchaptsev

**Comment by vchaptsev** [comment]
Wow, that was kinda hard 😄 
There was an ambiguity with `store` file and `store` directory, so:
```js
import store from '@/store'
```
actually imported the file (without any modules)

**Comment by ghost** [comment]
Ahhh! Thank you so much @vchaptsev - everything is working perfectly now. I really appreciate it. Hopefully I won't be bothering you for a while now 🥇
