### ISSUE TITLE
NGINX CORS configuration?

### ISSUE THREAD

**Issue by vladdoster** [vchaptsev/cookiecutter-django-vue#30]
Using Axios in a frontend component to retrieve a 3rd party API results in:

`Access to XMLHttpRequest at 'http://www.api.github.com/users' from origin 'http://localhost:8000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request`

I tried applying this solution :arrow_right: [enable-cors](https://enable-cors.org/server_nginx.html) with no success :cry: 

I assume this is because cors is not properly handled in the NGINX config. Has anyone had success getting past this hurdle? Any ideas what I could do?

**Comment by vchaptsev** [comment]
I think this issue is outdated 😢 
If not – please feel free to reopen (it would be great if you provided an example repo)
