### ISSUE TITLE
Frontend keeps crashing with message: Cannot find module '../package.json'

### ISSUE THREAD

**Issue by brienen** [vchaptsev/cookiecutter-django-vue#43]
After starting with dockers compose the frontend (docker) keeps crashing with message:   
frontend_1  | Error: Cannot find module '../package.json'

**Comment by io-ma** [comment]
Are you sure? It works for me. I just do ```docker-compose up --build``` and it works.

**Comment by vchaptsev** [comment]
if someone stumbles upon it – feel free to reopen
