### ISSUE TITLE
/usr/bin/env: ‘bash\r’: No such file or directory

### ISSUE THREAD

**Issue by Christian-Rau** [vchaptsev/cookiecutter-django-vue#51]
during docker-compose up --build

backend_1 /usr/bin/env: ‘bash\r’: No such file or directory
...
backend_1 exited with code 127

**Comment by fidex** [comment]
May happen when installing on Windows due to wrong line endings in the .sh files.
Fixed by using dos2unix or changing line endings on the files located in projectname/backend/scripts

**Comment by vchaptsev** [comment]
if someone wants to contribute – go for it :)

**Comment by Christian-Rau** [comment]
As fidex pointed out! SOLVED!
