### ISSUE TITLE
Will you support SSR?

### ISSUE THREAD

**Issue by supadrupa** [vchaptsev/cookiecutter-django-vue#9]
Is it possible to make a support of server-side rendering for Vue?
https://ssr.vuejs.org/en/

**Comment by vchaptsev** [comment]
Hello @supadrupa 
This is not in short-term plans, but it's obviously a useful feature.
Maybe you can contribute to make this happen faster? 😄

**Comment by vladimirmyshkovski** [comment]
@vchaptsev What do you think about introducing Nuxt.js into the project?

**Comment by supadrupa** [comment]
Nuxt is not released
https://github.com/nuxt/nuxt.js/releases

**Comment by vladimirmyshkovski** [comment]
@supadrupa I'm sure that there will be a release soon :)

**Comment by vchaptsev** [comment]
> @vchaptsev What do you think about introducing Nuxt.js into the project?


Isn't Nuxt only for Node.js?
Let's wait for the release and then we will think about it.

**Comment by vladimirmyshkovski** [comment]
@vchaptsev on my opinion yes, only with nodejs. 
Otherwise, it seems to me, without nodejs it is difficult to achieve SSR

But Nuxt makes it possible to generate static HTML files to be deployed on regular hosting.

**Comment by supadrupa** [comment]
This approach can be used 
https://gist.github.com/yyx990803/9bdff05e5468a60ced06c29c39114c6b#environment-agnostic-ssr
I think this is a bad practice.
Need a docker container with Node.js, 
any server(express, koa). 

The project will look like this:
isomorphic application(server side and client side)
nginx -> node.js(express or koa) -> vue.js

api backend.
nginx -> (uWSGI or gunicorn) -> django(django rest framework)

**Comment by sobolevn** [comment]
Having consistent and scalable `ssr` with `django` is almost impossible in my experience. 
Our approach is to spawn additional `node` container with the `nuxt`.
